name: NodeJS PR Check

on:
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Check Pull Request
    uses: umzug-meister/workflows/.github/workflows/node-pr-check.yml@main
    with:
      node_version: "22"
